#TO_MODIFY
version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_exam
  backend:
    build: ./backend
    ports:
      - "4001:3001"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DATABASE=${DATABASE_DATABASE}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_TABLE=${DATABASE_TABLE}
  frontend:
    build: ./frontend
    ports:
      - "4000:3000"
